### ISSUE TITLE
Workflow failing

### ISSUE THREAD

**Issue by kevburnsjr** [ncruces/go-coverage-report#1]
![image](https://user-images.githubusercontent.com/20638/228148960-dbb137ae-4b1a-494d-bf92-e293d535dba5.png)

The last line in the action is:
```
test ${{inputs.amend}} == "true" && git commit --amend --no-edit && git push --force-with-lease
```
That line returns status code 1 when `inputs.amend` is not "true" (the default).

```
> test false == "true"
> echo $?
1
```

PR incoming.

**Comment by ncruces** [comment]
Thanks, I thought I'd fixed this. Sorry.

**Comment by ncruces** [comment]
Just tested both (`amend` `true` and `false`); both seem to work.
I'll have to update the documentation.
Thanks for the report!

**Comment by kevburnsjr** [comment]
No worries. I was pinned to `main`. Rolling back to tag `v0.1.4` fixed it for me.

Pinning to `main` is not a great practice in general for precisely this reason. Might want to consider updating the [recommended usage](generally ) once v1 is complete.
```
    - name: Update coverage report
      uses: ncruces/go-coverage-report@main
```
Should probably read
```
    - name: Update coverage report
      uses: ncruces/go-coverage-report@v1
```

**Comment by ncruces** [comment]
Yes, I agree. I'll create a moving `v0` tag.

Not really comfortable with a `v1` yet, without more outside testing.

**Comment by ncruces** [comment]
BTW, meanwhile, you may also find the coverage chart option interesting. You can see it in action [here](https://github.com/ncruces/go-sqlite3/wiki/Test-coverage-report).

Thanks for the feedback, much appreciated!

**Comment by ncruces** [comment]
Did the tag, and updated the documentation.
Thanks again!
