### ISSUE TITLE
Feature request. Custom coverage report path

### ISSUE THREAD

**Issue by mgerasimchuk** [ncruces/go-coverage-report#10]
Thank you for your action, will be awesome to have a possibility to generate a multiple reports.

For example my case is to generate separate reports for unit and integration tests

**Comment by mgerasimchuk** [comment]
Hi @ncruces, will be glad if you have a look:  https://github.com/ncruces/go-coverage-report/pull/11

**Comment by ncruces** [comment]
I'm not entirely convinced about this.

Can you show me examples of repos showing different coverage metrics like this?

I'd like to get a better feel for the idea before commiting to the feature.

Sorry, I'm a bit afraid of feature spaghetti.

**Comment by mgerasimchuk** [comment]
Sure, take your time

Unfortunately I don't have examples with unit+integration separate badges.
But will try to add some description as a context.

Regarding the examples - I think a lot of solutions can have an integration test on the another level("uncoverable" level), like if you start your app wrapped in docker container in CI, and just send the real http requests it will be uncoverable case

Regarding my case, and why I want to separate it - It because the integration test involves almost all packages of the application during the tests, but the integration tests have the other type of testing quality, and cos of that I want to separate it from the unit tests.

**Comment by ncruces** [comment]
I don't question the separation between unit and integration tests. I just wonder if/why they merit different _coverage_ scores/reports.

I mean I have some projects where I have the opposite request, which is to run multiple rounds of tests (unit, integration), on multiple platforms (OSes, archs), under different configurations, and what I'd _really_ want would be to collect and merge all the `coverage.out` files and get a global coverage report (not segregation).

But I guess it doesn't harm. I'll probably merge this anyway, just give me a couple days.

**Comment by ncruces** [comment]
Would you mind trying `main`?
I made the mostly cosmetic changes, and hopefully didn't botch the retry logic.

**Comment by mgerasimchuk** [comment]
Sure, here it is:
- https://github.com/mgerasimchuk/protty/actions/runs/6694448244
- https://github.com/mgerasimchuk/protty/blob/master/.github/workflows/test-unit.yml

All works correctly (retrier logic too)

Thank you!

**Comment by ncruces** [comment]
Thanks! I'll tag the release then.
