### ISSUE TITLE
No coverage statement 

### ISSUE THREAD

**Issue by tok-kkk** [ncruces/go-coverage-report#6]
When I use the action to generate a coverage report, it shows 
```
warning: no packages being tested depend on matches for pattern /...
?   	github.com/catalogfi/blockchain/testutil	[no test files]
ok  	github.com/catalogfi/blockchain/btc	78.177s	coverage: [no statements]
```
It seems it did run the tests, but not sure why there're no statments.
The workflow file is [this](https://github.com/catalogfi/blockchain/actions/runs/6255571140/workflow)
The actual action can be found [here](https://github.com/catalogfi/blockchain/actions/runs/6255571140/job/16985118233)

I also tried the `coverage-file` param and it doesn't work 
```
cover: open ./cover.out: no such file or directory
```
The actual action can be found [here](https://github.com/catalogfi/blockchain/actions/runs/6255641415/job/16985297855)

**Comment by ncruces** [comment]
The first one is likely because your repo and module path are different (`github.com/catalogfi/blockchain` vs. `github.com/catalogfi/multichain`) and everything gets filtered out by `-coverpkg "$(go list)/..."`. Please confirm.

The second one, I have no idea. I don't use the feature myself. If you could troubleshoot it'd be extremely helpful.

**Comment by tok-kkk** [comment]
Still got `no statements` after fixing the module path 
Latest action [here](https://github.com/catalogfi/blockchain/actions/runs/6261039728/job/17000287557)

**Comment by ncruces** [comment]
It would've been helpful if you'd just run the `go test` command from the [script](https://github.com/ncruces/go-coverage-report/blob/v0.2.2/coverage.sh#L11) in a checkout of your project.

```sh
$ git clone https://github.com/catalogfi/blockchain
$ cd blockchain
$ go test ./... -coverpkg "$(go list)/..." -coverprofile coverage.out
```

Output:
```
warning: no packages being tested depend on matches for pattern /...
```

Digging a little deeper:
```sh
$ go list
no Go files in /Users/cruces/Desktop/blockchain
```

I don't have bandwidth track down your other bug, I'm sorry.
